name: GitHub to Codecommit Sync
if: (!(github.event.action == 'closed' && github.event.pull_request.merged != true))
on:
  push:
    tags-ignore:
      - "*"
    branches:
      - "**"
      - "!main"
      - "CLOUD-250"
  pull_request:
    branches:
      - main
    types: [opened, synchronize, closed]

  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.GH_CC_AWS_KEY  }}
          aws-secret-access-key: ${{ secrets.GH_CC_AWS_SECRET_KEY }}
          aws-region: eu-west-1

      - name: Sync up to CodeCommit
        uses: dms-jovan-stanoevski/githubsync@main
        with:
          repository_name: maksystem-internal-github-backup
          aws_region: eu-west-1
