# This workflow performs a backup of your repository to AWS S3 object storage

name: GitHub to AWS S3 backup

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ "CLOUD-250" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: S3 Backup
        uses: peter-evans/s3-backup@v1.0.2
        env:
          ACCESS_KEY_ID: ${{ secrets.GH_CC_AWS_KEY }}
          SECRET_ACCESS_KEY: ${{ secrets.GH_CC_AWS_SECRET_KEY }}
          MIRROR_TARGET: maksystem-internal-github-backup/dms-jovan-stanoevski/githubsync/
          STORAGE_SERVICE_URL: https://maksystem-internal-github-backup.s3.eu-west-1.amazonaws.com
        with:
          args: --overwrite --remove